# Copyright Hewlett Packard Enterprise Development LP.

services:
  chapel-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chapel-dev
    stdin_open: true
    tty: true
    volumes:
      - ../scorep-traces/:/traces
      - ../chpl:/workspace
    working_dir: /workspace
